apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: reviewbundles.sr.cattle.io
spec:
  group: sr.cattle.io
  names:
    kind: ReviewBundle
    plural: reviewbundles
    singular: reviewbundle
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.timestamp
      name: Timestamp
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              debug:
                type: boolean
              dev:
                type: boolean
              excludeClusters:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              includeClusters:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              parallelCollection:
                type: boolean
              sonobuoyNamespace:
                nullable: true
                type: string
              sonobuoyTimeout:
                type: integer
            type: object
          status:
            properties:
              timestamp:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
