apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportability-review-operator
  namespace: {{ template "sr.namespace" . }}
  labels:
    sr.cattle.io/operator: supportability-review-operator
spec:
  selector:
    matchLabels:
      sr.cattle.io/operator: supportability-review-operator
  template:
    metadata:
      labels:
        sr.cattle.io/operator: supportability-review-operator
    spec:
      serviceAccountName: supportability-review-operator-serviceaccount
      containers:
      - name: supportability-review-operator
        image: '{{ template "system_default_registry" . }}{{ .Values.image.sroperator.repository }}:{{ .Values.image.sroperator.tag }}'
        imagePullPolicy: IfNotPresent
        ports:
        - name: srmetrics
          containerPort: {{ .Values.alerts.metricsPort }}
        env:
        - name: SECURITY_SCAN_IMAGE
          value: {{ template "system_default_registry" . }}{{ .Values.image.securityScan.repository }}
        - name: SECURITY_SCAN_IMAGE_TAG
          value: {{ .Values.image.securityScan.tag }}
        - name: SONOBUOY_IMAGE
          value: {{ template "system_default_registry" . }}{{ .Values.image.sonobuoy.repository }}
        - name: SONOBUOY_IMAGE_TAG
          value: {{ .Values.image.sonobuoy.tag }}
        - name: CLUSTER_NAME
          value: '{{ .Values.global.cattle.clusterName }}'
        - name: SR_OPERATOR_DEBUG
          value: '{{ .Values.image.sroperator.debug }}'
        {{- if .Values.securityScanJob.overrideTolerations }}
        - name: SECURITY_SCAN_JOB_TOLERATIONS
          value: '{{ .Values.securityScanJob.tolerations | toJson  }}'
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector: {{ include "linux-node-selector" . | nindent 8 }}
{{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      tolerations: {{ include "linux-node-tolerations" . | nindent 8 }}
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
