apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rancher.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  url: {{ .Values.rancher.url | b64enc }}
  token: {{ .Values.rancher.token | b64enc }}
  srImageRepository: {{ .Values.rancher.srImageRepository | b64enc }}
  s3Endpoint: {{ .Values.s3.endpoint | b64enc }}
