apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  url: {{ .Values.rancherUrl | b64enc }}
  token: {{ .Values.rancherToken | b64enc }}
  repository: {{ .Values.image.repository | b64enc }}
